$schema: ../../../schema/mcp-agent.config.schema.json

execution_engine: asyncio
logger:
  transports: [console, file]
  level: info
  progress_display: true
  path_settings:
    path_pattern: "logs/muckrock-agent-{unique_id}.jsonl"
    unique_id: "timestamp"
    timestamp_format: "%Y%m%d_%H%M%S"

# MCP servers configuration (if needed for additional functionality)
mcp:
  servers:
    # You can add MCP servers here if needed, for example:
    # filesystem:
    #   command: "npx"
    #   args: ["-y", "@modelcontextprotocol/server-filesystem"]

# OpenAI configuration for LLM capabilities
openai:
  # API key should be in mcp_agent.secrets.yaml or environment variable
  default_model: "gpt-4o-mini"

# Anthropic configuration (optional)
anthropic:
  # API key should be in mcp_agent.secrets.yaml or environment variable
  default_model: "claude-3-haiku-20240307"